name: 'Build Quartz for GitHub Pages'
description: 'A simple GitHub Action for producing Quartz build artifacts'
author: 'konstfish'
branding:
  icon: 'book-open'
  color: 'purple'
inputs:
  source:
    description: 'The directory to build from'
    required: true
    default: ./
  destination:
    description: 'The directory to write output into'
    required: false
    default: ./_site
  page_title:
    description: 'Title of resulting Quartz Page'
    required: false
    default: Quartz
  page_base_url:
    description: 'Base URL (Required when setting icon or banner)'
    required: false
    default: 'example.com'
  quartz_config:
    description: 'Path to custom Quartz config file'
    required: false
  quartz_layout:
    description: 'Path to custom Quartz layout file'
    required: false
  quartz_icon:
    description: 'Path to custom Quartz Page icon (png)'
    required: false
  quartz_banner:
    description: 'Path to custom Quartz Page banner (png)'
    required: false
  quartz_custom_css:
    description: 'Path to custom Quartz Page css'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
